### ISSUE TITLE
Support watch mode

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/relative-deps#2]
It would be great if `relative-deps --watch` would automatically watch the relevant file paths of the relative dependencies, rebuilding and installing them when needed.

**Comment by jonstuebe** [comment]
I'd love to work on this feature as it would be really helpful for me to work on local development. I want to make sure and align with you first though on what you think makes sense.

For me a normal dev scenario would be something like this: `pkg-a` is the package I'm doing local development on. I have a terminal window open to that package's directory with a npm script running that watches for changes and does babel/typescript compiling.

Over in `project-a` I have `pkg-a` as a dependency using `relative-deps`. If `relative-deps` had a watch mode, in my mind I'd like it to known when the watch task in `pkg-a` is done compiling before packing, otherwise you'd have `relative-deps` doing multiple packs for each change which would be slow.

Any ideas on how to get around that? Or did you by chance have something else in mind?

cc/ @mweststrate

**Comment by mweststrate** [comment]
Sorry, missed the notif! But awesome! 

I didn't really think it true (read: really didn't), but I'd start pretty simple I think, and have relative-deps watch the pkg-a dir, and on change, wait a sec, calculate the hash as is done now, and to that a second later again, and repeat that process until the last two hashes are the same, assuming that means the package has stabilized, and start packing and all the other magic! If that works, that would be neat as it would require zero config :)

Thanks in advance!

**Comment by dvh91** [comment]
Got a small script for supporting the watch mode:

```js
const fs = require('fs');
const { spawn } = require('child_process');
const debounce = require('lodash/debounce');
const pkg = require('./package.json');

if (!pkg.relativeDependencies) return;

Object.entries(pkg.relativeDependencies).forEach(([packageName, path]) => {
    fs.watch(path, { recursive: true }, debounce(() => {
        buildRelativeDeps();
    }, 500))
});

function buildRelativeDeps() {
    const ls = spawn('yarn', ['relative-deps'], { stdio: 'inherit' });

    if (ls.stdout) {
        ls.stdout.on('data', (data) => {
            console.log(`${data}`);
        });

        ls.stderr.on('data', (data) => {
            console.error(`${data}`);
        });
    }
}
```

Hopefully, I'll open a MR with it soon but feel free to use it at the meantime. it works for me :)

**Comment by mweststrate** [comment]
Watch mode has been implemented by @dvh91 a little while back. Thanks again!
